server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
spring:         #配置在服务内的名字
  application:
    name: gateway
zuul:         #默认给每个service都配了
  routes:
    # 这里是路由id，随意写 # 这里是映射路径
    user-service:
      path:  /user/**
      serviceId: user-service
      strip-prefix: false
  ignored-services:
    - consumer-service
  #prefix: /api   #全局前缀
hystrix:  #熔断超时时长
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon: #feign负载均衡配置
  ConnectTimeout: 500 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms) 多长时间没读到数据