server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/taotao?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  # mapper-locations:
  type-aliases-package: cn.mahone.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    lease-renewal-interval-in-seconds: 30   #最小续约周期  心跳  默认30
    lease-expiration-duration-in-seconds: 90 #最小过期时长  默认90